### ISSUE TITLE
clr-icon attribute update results in NPE in some scenarios

### ISSUE THREAD

**Issue by Gesh4o** [vmware-clarity/ng-clarity#184]
## Describe the bug

Dynamically updating an attribute of an icon while shape attribute is empty or missing can result in NPE:
```
TypeError: Cannot read properties of null (reading 'split')
  at I._normalizeShape(/csp/gateway/portal/vendor.7fd679d72d21509b94c1.js:1:985089)
  at I.attributeChangedCallback(/csp/gateway/portal/vendor.7fd679d72d21509b94c1.js:1:986159)
  at G.value(/csp/gateway/portal/polyfills.25a724193ef080312c3d.js:1:29707)
  at G.value(/csp/gateway/portal/polyfills.25a724193ef080312c3d.js:1:24043)
  at I.attributeChangedCallback(/csp/gateway/portal/polyfills.25a724193ef080312c3d.js:1:23631)
  at jn.value(/csp/gateway/portal/vendor.7fd679d72d21509b94c1.js:1:455503)
  at It.value(/csp/gateway/portal/vendor.7fd679d72d21509b94c1.js:1:443435)
```

## How to reproduce

1. Open this stack blitz: https://stackblitz.com/edit/clarity-light-theme-clr12-cds5-1uka2y?file=src/app/app.component.html
2. Open browser console / clear console from messages
3. Click 'Change Shape'
4. See browser error

## Expected behavior
No error to be seen.

## Versions

**Clarity version:**
- [ x ] v12.x

**Framework:**
- [ x ] Angular 

**Framework version:**
_ie: Angular 12_

**Device:**

- Type:  MacBook
- Browser: Chrome
- Version: 102

## Additional notes

We discovered this bug during testing as we tried to dynamically set the 'shape' attribute based on a property coming from our backend. In some scenarios this property was undefined and we hit this error when we clicked on the icon. Please consider the stack-blitz as one of many potential ways to provoke the error.

Internal point of contact: stoimenovg

**Comment by ashleyryan** [comment]
Hey there - the `clr-icon` component is deprecated in favor of `cds-icon` - I forked your repo and was able to get it working using cds icon: https://stackblitz.com/edit/clarity-light-theme-clr12-cds5-gkcnmj
