### ISSUE TITLE
Datagrid unselectable row allows selection if user clicks on Manage columns

### ISSUE THREAD

**Issue by yogeshnagrath** [vmware-clarity/ng-clarity#503]
Describe the bug
Datagrid disabled row allows selection if user clicks on Manage columns

How to reproduce
1. Mark any row of the datagrid as unselectable.
2. Click on Manage columns.

Expected behavior
Selection should not be allowed for the unselectable row.

Actual behavior
Selection is allowed after clicking on Manage columns.

Versions
Clarity version:
v13.13.0

Framework version:
Angular 14

Additional notes
https://stackblitz.com/edit/clarity-dark-theme-clr13-cds6-ng14-7hupuz?file=src%2Fapp%2Fapp.component.html,src%2Fapp%2Fapp.component.ts

Following error is thrown in console:
zone.js:182 Uncaught Error: NG0100: ExpressionChangedAfterItHasBeenCheckedError: Expression has changed after it was checked. Previous value: 'true'. Current value: 'false'. Find more at https://angular.io/errors/NG0100
    at throwErrorIfNoChangesMode (core.mjs:9307:11)
    at bindingUpdated (core.mjs:14468:17)
    at pureFunction1Internal (core.mjs:22485:12)
    at Module.ɵɵpureFunction1 (core.mjs:22282:12)
    at ClrDatagridRow_ng_template_5_div_5_Template (clr-angular.mjs:15134:3531)
    at executeTemplate (core.mjs:12126:9)
    at refreshView (core.mjs:12011:13)
    at refreshEmbeddedViews (core.mjs:13039:17)
    at refreshView (core.mjs:12035:9)
    at refreshEmbeddedViews (core.mjs:13039:17)

https://user-images.githubusercontent.com/32540650/218466725-401c4cbc-2734-4b7c-a6a6-aa3644bd4076.mov

**Comment by kevinbuhmann** [comment]
Related: #475
